version: '3.7'

# add postgres service
services:
  postgres:
    image: postgres:15
    container_name: bowl-shop-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bowl_shop
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
