//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "customization")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub bowl_id: i32,
    pub name: String,
    #[sea_orm(column_type = "Float")]
    pub price: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bowl::Entity",
        from = "Column::BowlId",
        to = "super::bowl::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Bowl,
}

impl Related<super::bowl::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bowl.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
